BASE_PATH='/home/david/Coding/BibleTools3/Hebrew Scriptures'

BIBLE_BOOKS = {
    "Genesis": {"book_num": 1, "num_of_chaps": 50 },
    "Exodus" : {"book_num": 2, "num_of_chaps": 40},
    "Leviticus" : {"book_num": 3, "num_of_chaps": 27},
    "Numbers": {"book_num": 4, "num_of_chaps": 36},
    "Deuteronomy": {"book_num": 5, "num_of_chaps": 34},
    "Joshua": {"book_num": 6, "num_of_chaps": 24},
    "Judges": {"book_num": 7, "num_of_chaps": 21},
    "Ruth": {"book_num": 8, "num_of_chaps": 4},
    "1 Samuel": {"book_num": 9, "num_of_chaps": 31},
    "2 Samuel": {"book_num": 10, "num_of_chaps": 24},
    "1 Kings": {"book_num": 11, "num_of_chaps": 22},
    "2 Kings": {"book_num": 12, "num_of_chaps": 25},
    "1 Chronicles": {"book_num": 13, "num_of_chaps": 29},
    "2 Chronicles": {"book_num": 14, "num_of_chaps": 36},
    "Ezra": {"book_num": 15, "num_of_chaps": 10},
    "Nehemiah": {"book_num": 16, "num_of_chaps": 13},
    "Esther": {"book_num": 17, "num_of_chaps": 10},
    "Job": {"book_num": 18, "num_of_chaps": 42},
    "Psalms": {"book_num": 19, "num_of_chaps": 150},
    "Proverbs": {"book_num": 20, "num_of_chaps": 31},
    "Ecclesiastes": {"book_num": 21,"num_of_chaps": 12},
    "Song of Solomon": {"book_num": 22, "num_of_chaps": 8},
    "Isaiah": {"book_num": 23, "num_of_chaps": 66}, 
    "Jeremiah": {"book_num": 24, "num_of_chaps": 52},
    "Lamentations": {"book_num": 25, "num_of_chaps": 5},
    "Ezekiel": {"book_num": 26, "num_of_chaps": 48},
    "Daniel": {"book_num": 27, "num_of_chaps": 12},
    "Hosea": {"book_num": 28, "num_of_chaps": 14},
    "Joel": {"book_num": 29, "num_of_chaps": 3},
    "Amos": {"book_num": 30, "num_of_chaps": 9},
    "Obadiah": {"book_num": 31, "num_of_chaps": 1},
    "Jonah": {"book_num": 32, "num_of_chaps": 4},
    "Micah": {"book_num": 33, "num_of_chaps": 7}, 
    "Nahum": {"book_num": 34, "num_of_chaps": 3},
    "Habakkuk": {"book_num": 35, "num_of_chaps": 3},
    "Zephaniah": {"book_num": 36, "num_of_chaps": 3},
    "Haggai": {"book_num": 37, "num_of_chaps": 2},
    "Zechariah": {"book_num": 38, "num_of_chaps": 14},
    "Malachi": {"book_num": 39, "num_of_chaps": 4}
}

